sudo: false
language: node_js
node_js:
- node
install: npm ci
script:
- npm lint
- npm test
jobs:
  include:
  - stage: Produce Test Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      && rm -rf ./coverage
  - stage: npm release
    if: tag IS present
    node_js: '11'
    script: npm build
    before_deploy:
    - cd dist
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
deploy:
  provider: npm
  email: mmcgrath@mindedge.com
  api_key:
    secure: m+7ciPaxngap6qajDdwdqYs1IoD1xv2bAKAguotZFxxC5DRPNFCp5ZVIixjEeJBLWLmmuCeHgIwFfzylSParxayLu6NHLvRrbRwbFFvY0TytlEKzEj7cxP0dF0F1+z15yL5odxtFaMvu6F2aTgord7rsqQX7xOZmYWm3vjHSNL0H0mgjiD6OL8HQ2Gkwc0eGgzceiOBqPbTyoa1ftRhJLn7cjAFopO0vDIowvqQm/CzRPTp3fzp7gBuId18bYKzwAuBGNn+mRlqtKxbTxR55xZmjSdvLcZKqGILkRfxSDke+A6+QhHolA2DIs5g8goPTQ9tTbwGDYVVqBLHWeR///QUId7GY+KeAvwG2+XKaUsB2KkJfyMwGEAxgVdRfc+dlVZrYr+gOEq7kg5F3QAg6ZDzZLxV4ayp7HbyiUfKGvmwuJqIeDQuhcDN+/v3mnxl25dCmcr0WJkJ2MAAHOMgAjLC84iRAfzkOXXqtM1Fpv11jOIVskMLBZEhEuLpn5MIK4Tk19hjAa9F5s9lmCobHwFwKRMpGPFOTiDsjeYIwKtLwe0ZTzEpEqR9RcNkI5EaVNb9MJVo4sHjzYKLG/nEvdO3f4QgSHuaBdhFUk+TKEeW4l3S6Fi4sn7lVbj3jb8N7qiDltmzqlZSdE96YFZfID0IMX0og5ZHpKbH7H/JF420=
  on:
    tags: true
    repo: mindedge/api-transformer
