sudo: false

language: node_js
node_js:
  - 'node'

install: 
  - npm ci
script:
- yarn lint
- yarn test
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: npm build
    before_deploy:
    - cd dist
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
deploy:
  provider: npm
  email: mmcgrath@mindedge.com
  api_key:
    secure: KyNt8wBuDVbOb9fok9uyTYS2G+Ki4QyVEBD2iVmJre3SoLQfLr6ItvSqJhvj8x9ojPEj7sJDnMU3C3MP9btq93LMottsVNtQNDG7Pj/y6Ovieu1Y7cWHmreXyL18h92yKBJkfneu7aTBWCc6UB5V9SohNMj9Zc9jR2F/J4q151bqSc9T1O8j971JDD0zHVsuO1FQuaZDKBPX1rBQr08hnPwVF8RcWpEu9pbI5KGykoZhp11b53Skd6wpriHh8q+VwVh0tuMHW0BoRcf6ED9EESCg5FONN/EMQtyY804+rBrOxuItISfgJT/20qqkJjZEPmEL5QhJC3fT91alOF+laQPaRVGSAFGl3V4lryxMKOBrQKJpNdN/pD9miWWoQ3zgyxqEV2v3nhOxa2m/JlMBg2sQliei0POZ/W0R78pSHZcAhScOP5hTwzXFeKUSCXdQemM1PEGWDtu5rWrn54h0mNcR3RiK/W+79+2Po0EvRLI+vNUsHQcTWJyC0DQ324ChpwMevJT9vMtzDzK7z7p51GKWjATUA5n+Q/zcfCtoUByH8M1+AMlMPOKXCWhU1KFKuLTHlknMX/9Yv6J727cIbKXhGL6SAgSvP8oqjs5+Er9qqeknXVPu+foD+RkeFDAS78opgisdA2ifkGnU0AxEJSYSkPLOl5oiuPEV0x8MGCg=
  on:
    tags: true
    repo: mcmike-mindedge/typescript-learning
